create table if not exists farms (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  location text,
  created_at timestamptz default now()
);

create table if not exists devices (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid references farms(id) on delete cascade,
  device_code text unique not null,
  name text,
  type text default 'iot_node',
  status text default 'offline',
  last_seen_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists sensor_logs (
  id bigint generated by default as identity primary key,
  device_id uuid references devices(id) on delete cascade,
  temperature numeric,
  humidity numeric,
  co2 numeric,
  light numeric,
  soil_moisture numeric,
  created_at timestamptz default now()
);

create table if not exists device_commands (
  id bigint generated by default as identity primary key,
  device_id uuid references devices(id) on delete cascade,
  command text not null,
  payload jsonb default '{}'::jsonb,
  status text default 'pending',
  created_at timestamptz default now(),
  executed_at timestamptz
);

create table if not exists mushroom_images (
  id uuid primary key default gen_random_uuid(),
  device_id uuid references devices(id) on delete set null,
  image_url text not null,
  storage_path text,
  captured_at timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists ai_detections (
  id bigint generated by default as identity primary key,
  image_id uuid references mushroom_images(id) on delete cascade,
  model_name text,
  class_name text not null,
  confidence numeric,
  bbox jsonb,
  inference_time_ms integer,
  created_at timestamptz default now()
);

create table if not exists alerts (
  id bigint generated by default as identity primary key,
  device_id uuid references devices(id) on delete cascade,
  image_id uuid references mushroom_images(id) on delete set null,
  alert_type text not null,
  message text,
  severity text default 'medium',
  is_read boolean default false,
  created_at timestamptz default now()
);

alter table farms enable row level security;
alter table devices enable row level security;
alter table sensor_logs enable row level security;
alter table device_commands enable row level security;
alter table mushroom_images enable row level security;
alter table ai_detections enable row level security;
alter table alerts enable row level security;
